package com.wafflestudio.waffleseminar2024

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

const val MovieDataString1 = """
   [{
      "adult": false,
      "backdrop_path": "/Asg2UUwipAdE87MxtJy7SQo08XI.jpg",
      "genre_ids": [28, 14, 27],
      "id": 957452,
      "original_language": "en",
      "original_title": "The Crow",
      "overview": "10월 30일 '악마의 날', 까마귀의 저주로 죽음에서 부활한 에릭(빌 스카스가드)의 잔인한 복수극을 담은 다크 히어로 액션물",
      "popularity": 1940.634,
      "poster_path": "/58QT4cPJ2u2TqWZkterDq9q4yxQ.jpg",
      "release_date": "2024-08-21",
      "title": "더 크로우",
      "video": false,
      "vote_average": 5.376,
      "vote_count": 407
    },
    {
      "adult": false,
      "backdrop_path": "/zAqBIeO71BFL7bAtP5TFzVjVamy.jpg",
      "genre_ids": [10749, 18],
      "id": 1079091,
      "original_language": "en",
      "original_title": "It Ends with Us",
      "overview": "아버지의 장례식을 멋지게 망치고 아지트로 향한 ‘릴리’는 어딘가 위태롭지만 매력적인 남자 ‘라일’에게 순식간에 마음을 빼앗긴다. 새로운 도시에서 자신의 이름을 건 꽃집을 오픈한 릴리는 운명처럼 라일을 다시 만나게 되고 걷잡을 수 없는 사랑에 빠져든다. 그러던 어느 날, 어린 시절의 모든 상처를 알고 있는 첫사랑 ‘아틀라스’와 우연히 재회한 후 감당하기 벅찬 라일의 위협적인 모습을 목격하게 되고 완벽했던 관계가 순식간에 요동치면서 릴리는 피할 수 없는 선택의 기로에 서게 되는데… 외면하고 싶지만 마주해야 하는 사랑과 선택의 순간 올가을, 모두에게 위로와 용기를 선사하는 특별한 이야기!",
      "popularity": 1751.634,
      "poster_path": "/287MYoxjfINSyfaaV636Z2ioR36.jpg",
      "release_date": "2024-08-07",
      "title": "우리가 끝이야",
      "video": false,
      "vote_average": 6.9,
      "vote_count": 521
    },
    {
      "adult": false,
      "backdrop_path": "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
      "genre_ids": [28, 35, 878],
      "id": 533535,
      "original_language": "en",
      "original_title": "Deadpool & Wolverine",
      "overview": "히어로 생활에서 은퇴한 후, 평범한 중고차 딜러로 살아가던 ‘데드풀’이 예상치 못한 거대한 위기를 맞아 모든 면에서 상극인 ‘울버린’을 찾아가게 되며 펼쳐지는 도파민 폭발 액션 블록버스터.",
      "popularity": 1923.099,
      "poster_path": "/4Zb4Z2HjX1t5zr1qYOTdVoisJKp.jpg",
      "release_date": "2024-07-24",
      "title": "데드풀과 울버린",
      "video": false,
      "vote_average": 7.675,
      "vote_count": 3146
    },
    {
      "adult": false,
      "backdrop_path": "/dKvvW3euRwUY0Nyl6JBP5tXLPJW.jpg",
      "genre_ids": [16, 10751, 12, 35, 14, 18],
      "id": 1022789,
      "original_language": "en",
      "original_title": "Inside Out 2",
      "overview": "13살이 된 라일리의 행복을 위해 매일 바쁘게 머릿속 감정 컨트롤 본부를 운영하는 ‘기쁨’, ‘슬픔’, ‘버럭’, ‘까칠’, ‘소심’. 그러던 어느 날, 낯선 감정인 ‘불안’, ‘당황’, ‘따분’, ‘부럽’이가 본부에 등장하고, 언제나 최악의 상황을 대비하며 제멋대로인 ‘불안’이와 기존 감정들은 계속 충돌한다. 결국 새로운 감정들에 의해 본부에서 쫓겨나게 된 기존 감정들은 다시 본부로 돌아가기 위해 위험천만한 모험을 시작하는데…",
      "popularity": 1665.148,
      "poster_path": "/x2BHx02jMbvpKjMvbf8XxJkYwHJ.jpg",
      "release_date": "2024-06-11",
      "title": "인사이드 아웃 2",
      "video": false,
      "vote_average": 7.6,
      "vote_count": 3851
    },
    {
      "adult": false,
      "backdrop_path": "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
      "genre_ids": [16, 10751, 35, 28],
      "id": 519182,
      "original_language": "en",
      "original_title": "Despicable Me 4",
      "overview": "슈트-업 하고 악당 전담 처리반 AVL이 된 에이전트 미니언즈와 미니언즈 만큼 귀여운 그루 주니어가 태어나면서 더욱 완벽해진 그루 패밀리. 이들 앞에 과거 그루의 고등학교 동창이자 그에게 체포당했던 빌런 맥심이 등장하고, 오직 그루를 향한 복수심에 불타올라 탈옥까지 감행한 맥심은 그루 패밀리의 뒤를 바짝 추격하며 위협을 가하기 시작하는데... 과연 에이전트 미니언즈와 그루 패밀리는 맥심을 막아낼 수 있을까?",
      "popularity": 1259.623,
      "poster_path": "/5hl1PEpAvZ8Ok37kB7woIssHi3X.jpg",
      "release_date": "2024-06-20",
      "title": "슈퍼배드 4",
      "video": false,
      "vote_average": 7.166,
      "vote_count": 1752
    },
    {
      "adult": false,
      "backdrop_path": "/dTaqzXA1auKRUjHPQjR3u0W7Gfl.jpg",
      "genre_ids": [9648, 53],
      "id": 840705,
      "original_language": "en",
      "original_title": "Blink Twice",
      "overview": "",
      "popularity": 1009.255,
      "poster_path": "/lZGOK0I2DJSRlEPNOAFTSNxSjDD.jpg",
      "release_date": "2024-08-21",
      "title": "블링크 트와이스",
      "video": false,
      "vote_average": 6.719,
      "vote_count": 413
    },
    {
      "adult": false,
      "backdrop_path": "/tncbMvfV0V07UZozXdBEq4Wu9HH.jpg",
      "genre_ids": [28, 80, 53, 35],
      "id": 573435,
      "original_language": "en",
      "original_title": "Bad Boys: Ride or Die",
      "overview": "마이애미 강력반 최고의 콤비 마이크와 마커스. 가족 같은 하워드 반장이 사망 전 마약 카르텔 조직의 비리에 연루되었다는 뉴스 속보를 접하게 된다. 하지만 아무도 믿지 말라는 하워드 반장의 비밀 메시지를 받은 마이크와 마커스 형사는 사건의 진실을 밝히기 위해 위험한 수사를 시작한다. 서서히 드러나는 거대한 음모와 마주하게 된 나쁜 녀석들. 그러나 이들 역시 함정에 빠져 사건의 용의자로 지목되며 동료 경찰들은 물론 마약 카르텔 조직에게도 쫓기는 신세가 되고 마는데…",
      "popularity": 861.487,
      "poster_path": "/wIrhEUBWjRmZuL1Ix41cF2LhJrW.jpg",
      "release_date": "2024-06-05",
      "title": "나쁜 녀석들: 라이드 오어 다이",
      "video": false,
      "vote_average": 7.55,
      "vote_count": 2048
    },
    {
      "adult": false,
      "backdrop_path": "/mKOBdgaEFguADkJhfFslY7TYxIh.jpg",
      "genre_ids": [28, 878, 35],
      "id": 365177,
      "original_language": "en",
      "original_title": "Borderlands",
      "overview": "",
      "popularity": 873.768,
      "poster_path": "/865DntZzOdX6rLMd405R0nFkLmL.jpg",
      "release_date": "2024-08-07",
      "title": "보더랜드",
      "video": false,
      "vote_average": 5.883,
      "vote_count": 608
    },
    {
      "adult": false,
      "backdrop_path": "/blqiNjJefmY10Wx6y2vgJJWljJj.jpg",
      "genre_ids": [28, 53],
      "id": 949484,
      "original_language": "en",
      "original_title": "Hounds of War",
      "overview": "",
      "popularity": 973.295,
      "poster_path": "/lRBT73EWsiQPuqK3YS3BnBW0Zwi.jpg",
      "release_date": "2024-08-29",
      "title": "Hounds of War",
      "video": false,
      "vote_average": 6.314,
      "vote_count": 42
    },
    {
      "adult": false,
      "backdrop_path": "/A1dZ6faTjg0e6HYftBmEKujuXGQ.jpg",
      "genre_ids": [35, 14],
      "id": 917496,
      "original_language": "en",
      "original_title": "Beetlejuice Beetlejuice",
      "overview": "유령과 대화하는 영매로 유명세를 타게 된 리디아와 그런 엄마가 마음에 들지 않는 10대 딸 아스트리드. 할아버지 찰스의 갑작스러운 죽음으로 가족들은 함께 시골 마을에 내려간다. 유령을 보는 엄마가 마음에 들지 않는 아스트리드는 방황하던 중 함정에 빠져 저세상에 발을 들이게 되고 딸을 구하기 위해 리디아는 인간을 믿지 않는 저세상 슈퍼스타 비틀쥬스를 소환한다. 이루지 못한 리디아와의 결혼을 조건으로 내민 비틀쥬스. 이번엔 아스트리드가 비틀쥬스를 다시 저세상으로 보내야 하는데···",
      "popularity": 892.617,
      "poster_path": "/ypWQatJYyESE5PIzdlSdiOyWYja.jpg",
      "release_date": "2024-09-04",
      "title": "비틀쥬스 비틀쥬스",
      "video": false,
      "vote_average": 7.163,
      "vote_count": 710
    },
    {
      "adult": false,
      "backdrop_path": "/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg",
      "genre_ids": [18, 27, 878],
      "id": 933260,
      "original_language": "en",
      "original_title": "The Substance",
      "overview": "더 나은 버전의 당신을 꿈꿔본 적 있나요? 당신의 인생을 바꿔줄 신제품 ‘서브스턴스’. ‘서브스턴스’는 또 다른 당신을 만들어냅니다. 새롭고, 젊고, 더 아름답고, 더 완벽한 당신을. 단 한가지 규칙, 당신의 시간을 공유하면 됩니다. 당신을 위한 일주일, 새로운 당신을 위한 일주일, 각각 7일간의 완벽한 밸런스. 쉽죠? 균형을 존중한다면… 무엇이 잘못될 수 있을까요?",
      "popularity": 818.45,
      "poster_path": "/bnU26DZMzWWfpGZ9VUAAzSyou1u.jpg",
      "release_date": "2024-09-07",
      "title": "서브스턴스",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 134
    },
    {
      "adult": false,
      "backdrop_path": "/sjC29cgm4qZAnpOJQbYKCxDCcra.jpg",
      "genre_ids": [27, 878, 53],
      "id": 1062215,
      "original_language": "en",
      "original_title": "Afraid",
      "overview": "",
      "popularity": 784.491,
      "poster_path": "/gUREuXCnJLVHsvKXDH9fgIcfM6e.jpg",
      "release_date": "2024-08-28",
      "title": "어프레이드",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 130
    },
    {
      "adult": false,
      "backdrop_path": "/1pbV8uC6EUYOYnPqWfrQFPdAj1O.jpg",
      "genre_ids": [80, 28, 12, 53, 18],
      "id": 1147710,
      "original_language": "ko",
      "original_title": "하이재킹",
      "overview": "1971년 겨울 속초공항 여객기 조종사 태인과 규식은 김포행 비행에 나선다. 승무원 옥순의 안내에 따라 탑승 중인 승객들의 분주함도 잠시, 이륙한지 얼마 되지 않아 사제폭탄이 터지며 기내는 아수라장이 된다. 여객기를 통째로 납치하려는 용대는 조종실을 장악하고 무작정 북으로 기수를 돌리라 협박한다. 폭발 충격으로 규식은 한 쪽 시력을 잃고 이제 여객기를 조종할 수 있는 사람은 태인 뿐. 이들은 여객기를 무사히 착륙시키기 위한 사투를 시작하는데...",
      "popularity": 946.31,
      "poster_path": "/pLEenJ0I1XqySVezRdETf2n2w7H.jpg",
      "release_date": "2024-06-21",
      "title": "하이재킹",
      "video": false,
      "vote_average": 6.281,
      "vote_count": 32
    },
    {
      "adult": false,
      "backdrop_path": "/wSZbtiFIK1fkKZdSRtn2kz2Ttfd.jpg",
      "genre_ids": [28, 35, 80],
      "id": 1139817,
      "original_language": "ko",
      "original_title": "무도실무관",
      "overview": "힘든 사람을 그냥 지나치지 못하는 무술 유단자 이정도. 보호관찰관 김선민이 그런 정도를 알아보고 ‘무도실무관’을 권한다. 이제 전자발찌 대상자를 감시하며 범죄를 예방하는 그들의 활약이 펼쳐진다.",
      "popularity": 670.104,
      "poster_path": "/iuwUEZYNOHzhoNoRj6mcXd2xbYr.jpg",
      "release_date": "2024-09-10",
      "title": "무도실무관",
      "video": false,
      "vote_average": 7.924,
      "vote_count": 132
    },
    {
      "adult": false,
      "backdrop_path": "/7cDsJInZGnNC1IFQL5kgYsZSXr3.jpg",
      "genre_ids": [28, 80, 18],
      "id": 1186947,
      "original_language": "pt",
      "original_title": "Bandida - A Número Um",
      "overview": "악명높은 브라질 파벨라에서 성장한 젊은 여성이 사랑과 범죄 사이를 헤쳐 나간다. 위험천만한 갱단 간 경쟁과 배신 속에서 권력을 손에 넣기 위해 악착같이 발버둥 치며.",
      "popularity": 660.699,
      "poster_path": "/x1n3ZFBR7yuWrmts7GRZIcUtTVo.jpg",
      "release_date": "2024-06-20",
      "title": "밴딧: 넘버 원",
      "video": false,
      "vote_average": 6.2,
      "vote_count": 39
    },
    {
      "adult": false,
      "backdrop_path": "/tAwfoDyKiYa4KQdUp3DTMrEs4En.jpg",
      "genre_ids": [16, 878, 12, 10751],
      "id": 698687,
      "original_language": "en",
      "original_title": "Transformers One",
      "overview": "트랜스포머 시리즈의 주역, 옵티머스 프라임과 메가트론이 한때 형제와도 같은 친구사이였고, 그들이 어떻게 사이버트론 행성의 운명을 바꾸고 영원한 숙적이 되었는지 그 시작에 대한 이야기를 다루고 있다.",
      "popularity": 668.25,
      "poster_path": "/c2JXlWzvXegSda8qaATr8I47kMx.jpg",
      "release_date": "2024-09-11",
      "title": "트랜스포머 ONE",
      "video": false,
      "vote_average": 7.279,
      "vote_count": 68
    },
    {
      "adult": false,
      "backdrop_path": "/62zw627mH74rng9zc4tFfaR54KW.jpg",
      "genre_ids": [16, 878, 10751],
      "id": 1184918,
      "original_language": "en",
      "original_title": "The Wild Robot",
      "overview": "우연한 사고로 거대한 야생에 불시착한 로봇 '로즈'는 주변 동물들의 행동을 배우며 낯선 환경 속에 적응해 가던 중, 사고로 세상에 홀로 남겨진 아기 기러기 '브라이트빌'의 보호자가 된다. ‘로즈'는 입력되어 있지 않은 새로운 역할과 관계에 낯선 감정을 마주하고 겨울이 오기 전에 남쪽으로 떠나야 하는 '브라이트빌'을 위해 동물들의 도움을 받아 이주를 위한 생존 기술을 가르쳐준다. 그러나 선천적으로 몸집이 작은 '브라이트빌'은 짧은 비행도 힘겨워 하는데... 로봇 '로즈'와 아기 기러기 '브라이트빌'은 특별한 기적을 일으킬 수 있을까?",
      "popularity": 623.362,
      "poster_path": "/8dkuf9IuVh0VZjDTk7kAY67lU0U.jpg",
      "release_date": "2024-09-12",
      "title": "와일드 로봇",
      "video": false,
      "vote_average": 7.4,
      "vote_count": 34
    },
    {
      "adult": false,
      "backdrop_path": "/hZVIwxi6kK4KnpVPEWwdhG0cMM5.jpg",
      "genre_ids": [9648, 53],
      "id": 1012148,
      "original_language": "en",
      "original_title": "Chapel",
      "overview": "",
      "popularity": 594.057,
      "poster_path": "/94sIggRUBioP19m3vJQfV3lq6Z6.jpg",
      "release_date": "2024-01-17",
      "title": "Chapel",
      "video": false,
      "vote_average": 5.964,
      "vote_count": 14
    },
    {
      "adult": false,
      "backdrop_path": "/hdFIdXwS8FSN2wIsuotjW1mshI0.jpg",
      "genre_ids": [16, 35, 12, 10751],
      "id": 831815,
      "original_language": "en",
      "original_title": "Saving Bikini Bottom: The Sandy Cheeks Movie",
      "overview": "어느 날 누군가가 비키니 시티를 통째로 바다에서 퍼내 간다. 곧이어 도시를 구하겠다고 나서는 다람쥐 과학자 다람이. 친구인 네모바지 스폰지밥과 함께 텍사스로 모험을 떠난다.",
      "popularity": 570.099,
      "poster_path": "/30YnfZdMNIV7noWLdvmcJS0cbnQ.jpg",
      "release_date": "2024-10-18",
      "title": "다람이 무비: 비키니 시티를 구하라",
      "video": false,
      "vote_average": 0,
      "vote_count": 0
    },
    {
      "adult": false,
      "backdrop_path": "/cyKH7pDFlxIXluqRyNoHHEpxSDX.jpg",
      "genre_ids": [80, 28, 53, 18],
      "id": 646097,
      "original_language": "en",
      "original_title": "Rebel Ridge",
      "overview": "작은 도시를 방문한 전직 해병대원. 사촌의 보석 신청에 쓰려던 현금 가방을 관할 경찰에게 부당하게 압수당하자 그곳에 만연한 부패에 정면으로 맞서기로 한다.",
      "popularity": 579.031,
      "poster_path": "/ltAyMY5j73LtIqTzlFwPlfZb1K.jpg",
      "release_date": "2024-08-27",
      "title": "레블 리지",
      "video": false,
      "vote_average": 7.025,
      "vote_count": 707
    },
    {
      "adult": false,
      "backdrop_path": "/62zw627mH74rng9zc4tFfaR54KW.jpg",
      "genre_ids": [16, 878, 10751],
      "id": 1184918,
      "original_language": "en",
      "original_title": "The Wild Robot",
      "overview": "우연한 사고로 거대한 야생에 불시착한 로봇 '로즈'는 주변 동물들의 행동을 배우며 낯선 환경 속에 적응해 가던 중, 사고로 세상에 홀로 남겨진 아기 기러기 '브라이트빌'의 보호자가 된다. ‘로즈'는 입력되어 있지 않은 새로운 역할과 관계에 낯선 감정을 마주하고 겨울이 오기 전에 남쪽으로 떠나야 하는 '브라이트빌'을 위해 동물들의 도움을 받아 이주를 위한 생존 기술을 가르쳐준다. 그러나 선천적으로 몸집이 작은 '브라이트빌'은 짧은 비행도 힘겨워 하는데... 로봇 '로즈'와 아기 기러기 '브라이트빌'은 특별한 기적을 일으킬 수 있을까?",
      "popularity": 623.362,
      "poster_path": "/8dkuf9IuVh0VZjDTk7kAY67lU0U.jpg",
      "release_date": "2024-09-12",
      "title": "와일드 로봇",
      "video": false,
      "vote_average": 7.4,
      "vote_count": 33
    },
    {
      "adult": false,
      "backdrop_path": "/pysPTtYmTcQBlShcxXZwfs3Zp8H.jpg",
      "genre_ids": [878, 53, 27],
      "id": 1064028,
      "original_language": "en",
      "original_title": "Subservience",
      "overview": "아내 매기의 부재로 인해 AI가 탑재된 메이드를 들이기로 한 닉. 딸이 마음에 들어한 메이드를 집에 입주시키고 ‘앨리스’라는 이름을 붙인다.  청소, 요리, 장보기까지 완벽하게 집안일을 해내는 앨리스. 닉은 편리함을 느끼지만 그것도 잠시, 앨리스는 닉을 위한다는 명목 아래 아슬아슬한 행동을 이어간다.  “마음이 힘들면 능률이 떨어지죠. 제가 도와드릴게요”  아내 매기의 목소리까지 흉내 내는 앨리스와 금단의 선을 넘은 닉. 매기가 집으로 돌아오고 닉은 모든 것을 없었던 일로 하고 싶지만 앨리스는 닉에 대한 집착을 멈추지 않는다. 위험한 일도 서슴지 않으며 그녀는 폭주하기 시작하는데…",
      "popularity": 663.946,
      "poster_path": "/p0708UyphVhP7PfmAhf3Ds62VBk.jpg",
      "release_date": "2024-08-15",
      "title": "메이드",
      "video": false,
      "vote_average": 6.388,
      "vote_count": 116
    }]"""
const val MovieDataString2 = """
[{
    "adult": false,
    "backdrop_path": "/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg",
    "genre_ids": [28, 12, 53, 80],
    "id": 7451,
    "original_language": "en",
    "original_title": "xXx",
    "overview": "싸이렌이 온 거리를 울려 퍼지며 요란한 추격씬이 벌어지는 도중 한 녀석이 콜벳를 몰고 다리를 돌진, 200미터 높이에서 자동차 번지를 시도한다. 짜릿한 곡예를 선보인 후 낙하산을 펴고 유유히 사라지는 녀석의 이름은 '젠더 케이지'. 인터넷에 생방송된 이 장면은 전세계 네티즌들에게 열렬한 환호를 받는다. 또 한 번의 멋진 프로젝트로 영웅 대접을 받는 젠더 케이지. 그러나 파티가 무르익을 무렵, 갑자기 들이닥친 특수부대는 그에게 신경 안정제를 쏜 후 잠들게 한다. 깨어난 곳은 알 수 없는 레스토랑. 어리둥절한 그 곳은 갑자기 강도들의 침입장으로 돌변하고, 단숨에 상황을 정리해버린 그에게 기븐스가 축하 인사를 전한다. 미국 비밀첩보국 NSA의 1차 테스트를 통과한 것. 이후 또 다시 잠에서 깨어난 곳은 비행기 안. 2번째 테스트로 콜럼비아 마약 밀매상의 아지트에 던져진 젠더 케이지. 때마침 콜럼비아 정부와 마약상들의 충돌로 아수라장이 된 그곳에서 살아남기 위한 치열한 전쟁이 펼쳐지는데...  상황종료 후 유유히 나타난 기븐스는 NSA의 테스트를 유일하게 통과한 그에게 비밀요원이 되어줄 것을 부탁한다. 단 그렇지 않을 경우는 감옥행뿐이라는 단서를 둔다. 젠더 케이지의 코드명은 트리플 X. 첫번째 임무지는 비밀요원의 무덤이라는 별칭을 가지고 있는 도시 프라하. 이제 얼떨결에 비밀요원이 되어버린 트리플 X의 위험한 여정이 시작되는데.",
    "popularity": 464.536,
    "poster_path": "/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg",
    "release_date": "2002-08-09",
    "title": "트리플 엑스",
    "video": false,
    "vote_average": 5.935,
    "vote_count": 4203
},
{
    "adult": false,
    "backdrop_path": "/s6Fc6Dq55XYPL16GMoipJh8MVG4.jpg",
    "genre_ids": [28],
    "id": 1329912,
    "original_language": "en",
    "original_title": "Kung Fu Games",
    "overview": "",
    "popularity": 463.235,
    "poster_path": "/yjDdBBUEBMvyUiVohZ8T7W2IFl6.jpg",
    "release_date": "2024-08-23",
    "title": "Kung Fu Games",
    "video": false,
    "vote_average": 6.25,
    "vote_count": 16
},
{
    "adult": false,
    "backdrop_path": "/sIzZQdXY21sEks9lGkGuXzqdGSA.jpg",
    "genre_ids": [14, 35],
    "id": 4011,
    "original_language": "en",
    "original_title": "Beetlejuice",
    "overview": "신혼부부 아담과 바바라는 어처구니 없는 사고로 사망하고 행복했던 시절을 잊지 못해 유령이 되어 계속 집에 머문다. 그러던 어느날 찰스 가족이 이사오자 아담과 바바라는 그들을 쫓아낼 계획을 세운다. 찰스 가족을 쫓아내기 위해 유령소동을 벌였지만 번번이 실패한다. 아담부부는 찰스의 딸 리디아와 친해지고 리디아와 결혼을 꿈꾸는 사악한 장난꾸러기 비틀쥬스는 계속해서 사건을 벌이고, 일은 꼬여만 가는데...",
    "popularity": 426.88,
    "poster_path": "/nnl6OWkyPpuMm595hmAxNW3rZFn.jpg",
    "release_date": "1988-03-30",
    "title": "비틀쥬스",
    "video": false,
    "vote_average": 7.373,
    "vote_count": 7146
},
{
    "adult": false,
    "backdrop_path": "/veIyxxi5Gs8gvztLEW1Ysb8rrzs.jpg",
    "genre_ids": [28, 12, 878],
    "id": 823464,
    "original_language": "en",
    "original_title": "Godzilla x Kong: The New Empire",
    "overview": "두 타이탄의 전설적인 대결 이후 할로우 어스에 남은 콩은 드디어 애타게 찾던 동족을 발견하지만 그 뒤에 도사리고 있는 예상치 못한 위협에 맞닥뜨린다. 한편, 깊은 동면에 빠진 고질라는 알 수 없는 신호로 인해 깨어나고 푸른 눈의 폭군 스카 킹의 지배 아래 위기에 처한 할로우 어스를 마주하게 된다. 할로우 어스는 물론, 지구상에도 출몰해 전세계를 초토화시키는 타이탄들의 도발 속에서 고질라와 콩은 사상 처음으로 한 팀을 이뤄 반격에 나서기로 하는데…",
    "popularity": 344.746,
    "poster_path": "/4z1VMmlxHrziG45901esjB4dpIa.jpg",
    "release_date": "2024-03-27",
    "title": "고질라 X 콩: 뉴 엠파이어",
    "video": false,
    "vote_average": 7.164,
    "vote_count": 3609
},
{
    "adult": false,
    "backdrop_path": "/ndZ0rmPqY8AtXLdvF14hjBhkuDj.jpg",
    "genre_ids": [27, 9648, 878],
    "id": 869291,
    "original_language": "en",
    "original_title": "Cuckoo",
    "overview": "그레첸은 아빠의 새 가족과 함께 살기 위해 미국에서 독일 바바리아 지방 알프스 산간의 한 리조트에 도착한다. 여전히 미국에서의 생활을 그리워하는 그녀에게 고즈넉한 미드센추리 모던 스타일의 리조트는 낯설고 이상한 공간이다. 리조트 주인 쾨니그도 친절하지만, 어딘가 께름직하다. 예상치 못한 사건들이 이어지고 낯선 인물들이 등장하면서 엄청난 비밀이 드러나기 시작하고 그레첸은 살아남기 위한 혈투에 뛰어든다.",
    "popularity": 450.94,
    "poster_path": "/mpryn3TuSPNG5ELRxyrKfblxJ9R.jpg",
    "release_date": "2024-08-02",
    "title": "뻐꾹!",
    "video": false,
    "vote_average": 5.531,
    "vote_count": 96
},
{
    "adult": false,
    "backdrop_path": "/8vqmXMXsDVSkw6w3asP4Ie8JlSl.jpg",
    "genre_ids": [27],
    "id": 1091267,
    "original_language": "en",
    "original_title": "The Well",
    "overview": "한 젊은 미술품 복원사가 중세 시대의 그림을 원래의 아름다움으로 복원하기 위해 작은 마을로 향합니다. 그러나 그림에 깃든 저주로 인해 그녀의 목숨은 위태로워지는데...",
    "popularity": 406.348,
    "poster_path": "/zK1X5T7gAdXxLFhj0hYyCTVrvpU.jpg",
    "release_date": "2024-08-01",
    "title": "더 웰",
    "video": false,
    "vote_average": 6.011,
    "vote_count": 45
},
{
    "adult": false,
    "backdrop_path": "/7aPrv2HFssWcOtpig5G3HEVk3uS.jpg",
    "genre_ids": [28, 12, 53],
    "id": 718821,
    "original_language": "en",
    "original_title": "Twisters",
    "overview": "뉴욕 기상청 직원 케이트는 대학 시절 토네이도에 맞서다 소중한 사람들을 잃고 죄책감에 살고 있다. 그런 그녀 앞에 옛 친구 하비가 찾아와 토네이도를 소멸시킬 수 있는 획기적인 방법을 제안한다.  고민 끝에 합류하게 된 케이트는 하비와 오클라호마로 향하고, 일명 토네이도 카우보이라 불리는 유명 인플루언서 타일러를 만난다. 마치 자연을 정복한 듯이 자신감 넘치는 타일러와 매사 부딪히게 되는 케이트. 어느 날, 모든 것을 집어삼킬 거대한 토네이도가 휘몰아칠 것을 감지하게 되는데…",
    "popularity": 455.434,
    "poster_path": "/w5mXdM9AIf7urUtoUVYjABdp3g8.jpg",
    "release_date": "2024-07-10",
    "title": "트위스터스",
    "video": false,
    "vote_average": 6.977,
    "vote_count": 1464
},
{
    "adult": false,
    "backdrop_path": "/2wrdcWrAN53Pl7ahBWMIKMzXBFF.jpg",
    "genre_ids": [16, 28, 12, 14, 878],
    "id": 1134424,
    "original_language": "th",
    "original_title": "นักรบมนตรา: ตำนานแปดดวงจันทร์",
    "overview": "",
    "popularity": 448.898,
    "poster_path": "/mynbrkIAAWw8OVVNAqC75vPwKqg.jpg",
    "release_date": "2023-10-11",
    "title": "만트라 워리어: 8개 달의 전설",
    "video": false,
    "vote_average": 6.565,
    "vote_count": 23
},
{
    "adult": false,
    "backdrop_path": "/1wP1phHo2CROOqzv7Azs0MT5esU.jpg",
    "genre_ids": [16, 35, 10751, 12, 28],
    "id": 748783,
    "original_language": "en",
    "original_title": "The Garfield Movie",
    "overview": "세상귀찮 집냥이, 바쁘고 험난한 세상에 던져졌다! 집사 ‘존’과 반려견 ‘오디’를 기르며 평화로운 나날을 보내던 집냥이 ‘가필드’. 어느 날, 험악한 길냥이 무리에게 납치당해 냉혹한 거리로 던져진다. 돌봐주는 집사가 없는 집 밖 세상은 너무나도 정신없게 돌아가고 길에서 우연히 다시 만난 아빠 길냥이 ‘빅’은 오히려 ‘가필드’를 위기에 빠지게 하는데… 험난한 세상, 살아남아야 한다!",
    "popularity": 479.505,
    "poster_path": "/57g3pHYi3p0JNVO1LkcyYbeMDBf.jpg",
    "release_date": "2024-04-30",
    "title": "가필드 더 무비",
    "video": false,
    "vote_average": 7.119,
    "vote_count": 966
},
{
    "adult": false,
    "backdrop_path": "/ahYDVW0ReOTKI6sbI6du9SoXdX9.jpg",
    "genre_ids": [28],
    "id": 666035,
    "original_language": "en",
    "original_title": "Wanted Man",
    "overview": "열혈 수사로 기소 위기에 처한 베테랑 형사. 마약 단속반 살인사건의 목격자를 미국으로 이송하는 일급비밀 미션으로 멕시코에 급파된다. 목격자 인도와 함께 카르텔의 공격이 시작되고 사막에 완전 포위되어 생존을 건 추격전을 벌인다. 목표는 단 하나. 살아서 돌아가야 한다. 피할 수 없는 전쟁이 선포된다. 지킬 수 없다면 모조리 부숴버린다!",
    "popularity": 370.465,
    "poster_path": "/yIOmBJX2CkeVD783uC7DZWdzH1T.jpg",
    "release_date": "2024-04-01",
    "title": "원티드 맨",
    "video": false,
    "vote_average": 7.073,
    "vote_count": 62
},
{
    "adult": false,
    "backdrop_path": "/okVLmXL5y18dfN2R4ufMZEGaeCd.jpg",
    "genre_ids": [28, 80, 53, 18],
    "id": 1160018,
    "original_language": "hi",
    "original_title": "किल",
    "overview": "질주하는 야간열차에 잠입한 무장 강도 집단.열차 승객들을 구하기 위해 나선 특수 요원. 문, 커튼, 손잡이. 손에 잡히는 모든 것이 무기가 된다!  40명의 빌런, 52개의 무기, 9번의 위기! 용서도, 자비도 없다! 짜릿하고 무자비한 복수가 시작된다!",
    "popularity": 405.889,
    "poster_path": "/hJxdfkQVSzM67uKjInnZA2mJTua.jpg",
    "release_date": "2024-07-03",
    "title": "킬",
    "video": false,
    "vote_average": 7.124,
    "vote_count": 185
},
{
    "adult": false,
    "backdrop_path": "/2RVcJbWFmICRDsVxRI8F5xRmRsK.jpg",
    "genre_ids": [27, 878, 53],
    "id": 762441,
    "original_language": "en",
    "original_title": "A Quiet Place: Day One",
    "overview": "평균 소음 90 데시벨을 자랑하는 미국 최대도시 뉴욕, 고양이 프로도와 함께 간만에 외출을 나온 사미라는 공연을 보고 돌아가던 중 하늘에서 떨어져 내리는 섬광을 목격하고 곧 사람들을 닥치는 대로 공격하는 정체불명 괴생명체의 출현에 충격에 휩싸인다. 아수라장이 된 뉴욕 도심에 ‘절대 소리 내지 말라’는 안내방송이 울려퍼지는 가운데 맨해튼의 모든 다리가 폭격으로 끊어지고, 사람들은 온갖 위협이 도사리는 도시에 고립되고 만다. 살아남기 위해 홀로 사투를 벌이던 '사미라'는 우연히 또 다른 생존자 에릭을 만나고 두 사람은 괴생명체를 피해 지하철역부터 시가지, 할렘까지 숨죽인 여정을 이어 나가는데…",
    "popularity": 428.905,
    "poster_path": "/eufjDFIHtFSmcblWpvw5BiNzmO6.jpg",
    "release_date": "2024-06-26",
    "title": "콰이어트 플레이스: 첫째 날",
    "video": false,
    "vote_average": 6.801,
    "vote_count": 1822
},
{
    "adult": false,
    "backdrop_path": "/9juRmk8QjcsUcbrevVu5t8VZy5G.jpg",
    "genre_ids": [28, 12, 80, 53],
    "id": 923667,
    "original_language": "cn",
    "original_title": "九龍城寨之圍城",
    "overview": "1980년대 홍콩 내 위험하고 불가사의했던 무법지대, 구룡성채! 악명 높은 갱단에게서 도망치려던 '진락군'은 우연히 구룡성채로 도망가게 되고,  성채의 일원들의 도움을 받아 목숨을 건진다. 그 후 '진락군'은 성채의 일원이 되어 생애 첫 보금자리를 가지게 되는데...  행복도 잠시, 오랫동안 성채를 노린 악당들이 들이닥치고 그들은 최후의 전쟁을 시작하게 된다.",
    "popularity": 394.557,
    "poster_path": "/aUXq8aK2UX1CoQbxUi4fyioPOgH.jpg",
    "release_date": "2024-04-23",
    "title": "구룡성채: 무법지대",
    "video": false,
    "vote_average": 6.608,
    "vote_count": 158
},
{
    "adult": false,
    "backdrop_path": "/fqv8v6AycXKsivp1T5yKtLbGXce.jpg",
    "genre_ids": [878, 12, 28],
    "id": 653346,
    "original_language": "en",
    "original_title": "Kingdom of the Planet of the Apes",
    "overview": "진화한 유인원과 퇴화된 인간들이 살아가는 땅. 유인원 리더 프록시무스는 완전한 군림을 위해 인간들을 사냥하며 자신의 제국을 건설한다. 한편, 또 다른 유인원 노아는 우연히 숨겨진 과거의 이야기와 시저의 가르침을 듣게 되고 인간과 유인원이 함께 할 새로운 세상을 꿈꾼다. 어느 날 그의 앞에 나타난 의문의 한 인간 소녀. 노아는 그녀와 함께 자유를 향한 여정을 시작하게 되는데…",
    "popularity": 423.602,
    "poster_path": "/plNOSbqkSuGEK2i15A5btAXtB7t.jpg",
    "release_date": "2024-05-08",
    "title": "혹성탈출: 새로운 시대",
    "video": false,
    "vote_average": 7.1,
    "vote_count": 2919
},
{
    "adult": false,
    "backdrop_path": "/kXPCUNo7ALN0S03AbmTY9Ln6Fbc.jpg",
    "genre_ids": [27, 878, 53],
    "id": 1201734,
    "original_language": "en",
    "original_title": "God of Pain",
    "overview": "",
    "popularity": 395.983,
    "poster_path": "/dF0FAFCfILaor5RBqdNHq24OaIn.jpg",
    "release_date": "2024-08-20",
    "title": "God of Pain",
    "video": false,
    "vote_average": 8,
    "vote_count": 6
},
{
    "adult": false,
    "backdrop_path": "/vJk9DOLgP23jO5mBnPHE93MFgYu.jpg",
    "genre_ids": [12, 10751, 14, 35],
    "id": 826510,
    "original_language": "en",
    "original_title": "Harold and the Purple Crayon",
    "overview": "모험심이 강한 해롤드는 책 속에서는 무엇이든 그리기만 하면 현실로 만들 수 있어요. 해롤드는 성장하여 책 속 페이지에서 벗어나 현실 세계로 나온 후 현실 생활에 대해 배울 것이 많다는 것을 알게 됩니다.",
    "popularity": 347.898,
    "poster_path": "/dEsuQOZwdaFAVL26RjgjwGl9j7m.jpg",
    "release_date": "2024-07-31",
    "title": "해럴드와 보라색 크레용",
    "video": false,
    "vote_average": 7.1,
    "vote_count": 132
},
{
    "adult": false,
    "backdrop_path": "/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg",
    "genre_ids": [878, 12, 28],
    "id": 667538,
    "original_language": "en",
    "original_title": "Transformers: Rise of the Beasts",
    "overview": "전 우주의 행성을 집어삼키는 절대자, ‘유니크론’의 부하 ‘스커지’는 ‘테러콘’들을 이끌고 지구에 당도한다. 그에 맞서기 위해 지구에 정체를 숨기고 있던 트랜스포머 ‘오토봇’ 군단이 모습을 드러내고 또 다른 트랜스포머 진영인 ‘맥시멀’과 힘을 합친다. 옵티머스 프라임이 이끄는 ‘오토봇’과 옵티머스 프라이멀을 중심으로 한 ‘맥시멀’. 모두의 운명을 건 그들의 압도적 전투가 시작된다!",
    "popularity": 267.861,
    "poster_path": "/chUZNPNd7EiETSB4xBGykXhuXRr.jpg",
    "release_date": "2023-06-06",
    "title": "트랜스포머: 비스트의 서막",
    "video": false,
    "vote_average": 7.307,
    "vote_count": 4485
},
{
    "adult": false,
    "backdrop_path": "/bizhlTVjifYQUu4Xrdt7m3TYr7d.jpg",
    "genre_ids": [80, 27, 53],
    "id": 1226578,
    "original_language": "en",
    "original_title": "Longlegs",
    "overview": "FBI 요원 리 하커는 찾기 힘든 연쇄 살인범의 미해결 사건에 배정된 재능 있는 신입 요원이다. 사건이 복잡하고, 오컬트 관습과의 연관성을 밝혀내는 증거가 사라지면서, 하커는 무자비한 살인범과의 개인적 연관성을 발견하고, 그가 다시 공격하기 전에 그를 막기 위해 시간과 경주해야 한다.",
    "popularity": 370.122,
    "poster_path": "/maGzdLxWjgLgr4iOZ26Rfpst29A.jpg",
    "release_date": "2024-05-31",
    "title": "롱레그스",
    "video": false,
    "vote_average": 6.682,
    "vote_count": 927
},
{
    "adult": false,
    "backdrop_path": "/tCQfubckzzcuCbsGugkpLhfjS5z.jpg",
    "genre_ids": [28, 53, 80],
    "id": 970347,
    "original_language": "en",
    "original_title": "The Killer",
    "overview": "한 킬러가 아름다운 젊은 가수의 시력을 되찾기 위해 복수를 시도한다. 첩혈쌍웅의 리메이크 작",
    "popularity": 376.961,
    "poster_path": "/6PCnxKZZIVRanWb710pNpYVkCSw.jpg",
    "release_date": "2024-08-22",
    "title": "더 킬러",
    "video": false,
    "vote_average": 6.63,
    "vote_count": 231
},
{
    "adult": false,
    "backdrop_path": "/AjykZQ9ncgyJoHpMTquDRUAv5VO.jpg",
    "genre_ids": [18],
    "id": 592695,
    "original_language": "sv",
    "original_title": "Pleasure",
    "overview": "벨라 체리는 포르노 영화 배우의 꿈을 안고 로스앤젤레스에 도착하지만,  그녀는 그녀의 야망과 교활함을 활용하여 이 매혹적이고 독특한 세계의  정상에 오르기 위해 노력하지만 그런 명성이 쉽게 오지 않는다는 것을 곧 알게 된다.",
    "popularity": 345.435,
    "poster_path": "/t3SEI2YI81oO3nEgjJ9jMAIKApY.jpg",
    "release_date": "2021-10-08",
    "title": "플레저",
    "video": false,
    "vote_average": 6.231,
    "vote_count": 516
},
{
    "adult": false,
    "backdrop_path": null,
    "genre_ids": [10749, 18],
    "id": 482600,
    "original_language": "ko",
    "original_title": "일본 엄마",
    "overview": "얼굴은 청순, 가슴은 D컵, 밤 기술은 퍼펙트! \"\"아들아, 이제부터 네 여친이 아니라 엄마다.\"\r 아들 기호가 결혼하겠다며 일본에서 데려온 그녀, 유키. 그러나 기호는 한국에 오자 전 여친을 만나며 바람을 피우기 시작한다. 처음에는 예비 며느리를 달래는 마음으로 유키를 위로하던 민철은 어느 순간부터 자신이 유키를 여자로 보고 있다는 사실을 깨닫는다. 결국, 기호 몰래 민철과 유키의 뜨거운 정사가 펼쳐지는데...",
    "popularity": 310.229,
    "poster_path": "/hq1EaYIqUNrPM3QFYAbnH2UHoX8.jpg",
    "release_date": "2017-02-09",
    "title": "일본 엄마",
    "video": false,
    "vote_average": 6.529,
    "vote_count": 17
},
{
    "adult": false,
    "backdrop_path": "/t3LicFpYHeYpwqm7L5wDpd22hL5.jpg",
    "genre_ids": [12, 14],
    "id": 671,
    "original_language": "en",
    "original_title": "Harry Potter and the Philosopher's Stone",
    "overview": "해리 포터는 위압적인 버논 숙부와 냉담한 이모 페투니아, 욕심 많고 버릇없는 사촌 더즐리 밑에서 갖은 구박을 견디며 계단 밑 벽장에서 생활한다. 이모네 식구들 역시 해리와의 동거가 불편하기는 마찬가지. 이모 페투니아에겐 해리가 이상한 언니 부부에 관한 기억을 떠올리게 만드는 달갑지 않은 존재다. 11살 생일이 며칠 앞으로 다가왔지만 한번도 생일파티를 치르거나 제대로 된 생일선물을 받아 본 적이 없는 해리로서는 특별히 신날 것도 기대 할 것도 없다. 11살 생일을 며칠 앞둔 어느 날 해리에게 초록색 잉크로 쓰여진 한 통의 편지가 배달된다. 그 편지의 내용은 다름 아닌 해리의 11살 생일을 맞이하여 호그와트에서 보낸 입학 초대장이었다. 그리고 해리의 생일을 축하하러 온 거인 해그리드는 해리가 모르고 있었던 해리의 진정한 정체를 알려주는데...",
    "popularity": 265.253,
    "poster_path": "/unEtC8uWn2lcQLnwKG9PZJX0h0c.jpg",
    "release_date": "2001-11-16",
    "title": "해리 포터와 마법사의 돌",
    "video": false,
    "vote_average": 7.913,
    "vote_count": 27106
}]"""
const val MovieDataString3 = """
[
    {
      "adult": false,
      "backdrop_path": "/wQ60FXOHnVimJo6Bpdk6VU0qaP6.jpg",
      "genre_ids": [12, 10751],
      "id": 966576,
      "original_language": "en",
      "original_title": "The Quest for Tom Sawyer's Gold",
      "overview": "",
      "popularity": 387.337,
      "poster_path": "/zceLrHeYOgJHw1tw6MUi15N2NUz.jpg",
      "release_date": "2023-06-22",
      "title": "The Quest for Tom Sawyer's Gold",
      "video": false,
      "vote_average": 4.65,
      "vote_count": 10
    },
    {
      "adult": false,
      "backdrop_path": "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
      "genre_ids": [878, 12],
      "id": 693134,
      "original_language": "en",
      "original_title": "Dune: Part Two",
      "overview": "황제의 모략으로 멸문한 가문의 유일한 후계자 폴. 어머니 레이디 제시카와 간신히 목숨만 부지한 채 사막으로 도망친다. 그곳에서 만난 반란군들과 숨어 지내다 그들과 함께 황제의 모든 것을 파괴할 전투를 준비한다. 한편 반란군들의 기세가 높아질수록 불안해진 황제와 귀족 가문은 잔혹한 암살자 페이드 로타를 보내 반란군을 몰살하려 하는데…",
      "popularity": 209.86,
      "poster_path": "/8uUU2pxm6IYZw8UgnKJyx7Dqwu9.jpg",
      "release_date": "2024-02-27",
      "title": "듄: 파트 2",
      "video": false,
      "vote_average": 8.163,
      "vote_count": 5292
    },
    {
      "adult": false,
      "backdrop_path": "/h9YlRHAZWOWtGonllmj6JJg1FrE.jpg",
      "genre_ids": [28, 12, 16, 10751, 14],
      "id": 588648,
      "original_language": "zh",
      "original_title": "Dragonkeeper",
      "overview": "",
      "popularity": 335.768,
      "poster_path": "/hfdmvuLY8vADVthLNyn5EUO1ria.jpg",
      "release_date": "2024-04-11",
      "title": "Dragonkeeper",
      "video": false,
      "vote_average": 7.245,
      "vote_count": 106
    },
    {
      "adult": false,
      "backdrop_path": "/n3JeGELHa9V6k9mL81ItMxWLSS6.jpg",
      "genre_ids": [28, 53, 27],
      "id": 1129598,
      "original_language": "en",
      "original_title": "Prey",
      "overview": "극단주의 무장 단체의 위협을 받은 한 젊은 부부는 칼라하리 사막의 선교 기지를 떠나야 한다. 부패한 밀수업자가 조종하는 허술한 비행기에 겨우 탑승하여 탈출을 시도하지만,비행기가 추락하며 더 큰 위협에 직면하게 된다. 그들이 불시착한 곳은 사자, 표범, 하이에나 같은 맹수들이 서식하는 칼라하리 사막 한가운데…무장 단체에게 추적당하는 승객들은 인간과 야생 동물 모두와 싸워야만 한다. 과연 누가 이 치열한 생존 싸움에서 살아남을 것인가?",
      "popularity": 333.871,
      "poster_path": "/dcUmzoiHChYmtef2yEe06QcML5o.jpg",
      "release_date": "2024-03-15",
      "title": "더 라이언: 사막의 생존자들",
      "video": false,
      "vote_average": 6.318,
      "vote_count": 234
    },
    {
      "adult": false,
      "backdrop_path": "/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg",
      "genre_ids": [28, 12, 878],
      "id": 786892,
      "original_language": "en",
      "original_title": "Furiosa: A Mad Max Saga",
      "overview": "문명 붕괴 45년 후, 황폐해진 세상 속 누구에게도 알려지지 않은 풍요가 가득한 녹색의 땅에서 자란 퓨리오사는 바이커 군단의 폭군 디멘투스의 손에 모든 것을 잃고 만다. 가족도 행복도 모두 빼앗기고 세상에 홀로 내던져진 퓨리오사는 반드시 고향으로 돌아가겠다는 어머니와의 약속을 지키기 위해 인생 전부를 건 복수를 시작하는데...",
      "popularity": 335.888,
      "poster_path": "/zaUFDdJidS4Nyyd6jb2Ok3Kq4Vo.jpg",
      "release_date": "2024-05-22",
      "title": "퓨리오사: 매드맥스 사가",
      "video": false,
      "vote_average": 7.558,
      "vote_count": 3125
    },
    {
      "adult": false,
      "backdrop_path": "/aTzpE6136X7Rpx9RtZIDcsjduy0.jpg",
      "genre_ids": [28, 80, 53],
      "id": 1005076,
      "original_language": "en",
      "original_title": "Duchess",
      "overview": "",
      "popularity": 345.643,
      "poster_path": "/5TR7JlJbKucNSq84rkbnjLd1JB5.jpg",
      "release_date": "2024-08-01",
      "title": "Duchess",
      "video": false,
      "vote_average": 6.5,
      "vote_count": 15
    },
    {
      "adult": false,
      "backdrop_path": "/lntyt4OVDbcxA1l7LtwITbrD3FI.jpg",
      "genre_ids": [18, 10749],
      "id": 1010581,
      "original_language": "es",
      "original_title": "Culpa mía",
      "overview": "노아는 남자 친구와 친구들이 있는 동네를 뒤로하고 엄마의 새 부자 남편 저택으로 이사를 가게 된다. 의붓오빠 닉과는 첫 만남부터 삐걱댔지만 곧 서로에게 이끌려 금지된 관계를 맺는다. 반항심과 고뇌로 가득 찬 그들의 인생은 송두리째 흔들리고 둘은 결국 뜨거운 사랑에 빠진다.",
      "popularity": 299.382,
      "poster_path": "/duT8Vks5FXwDkpxoR84xb2a6VB6.jpg",
      "release_date": "2023-06-08",
      "title": "나의 잘못",
      "video": false,
      "vote_average": 7.935,
      "vote_count": 2911
    },
    {
      "adult": false,
      "backdrop_path": "/3EIYw4aJImgsvJsb0ybhOzLk6J3.jpg",
      "genre_ids": [28, 18],
      "id": 1066262,
      "original_language": "en",
      "original_title": "The Convert",
      "overview": "",
      "popularity": 289.059,
      "poster_path": "/e5ZqqPlhKstzB4geibpZh38w7Pq.jpg",
      "release_date": "2024-03-14",
      "title": "더 컨버트",
      "video": false,
      "vote_average": 6.104,
      "vote_count": 77
    },
    {
      "adult": false,
      "backdrop_path": "/4yrOyO3N55XazHQXXYoqiiPQd40.jpg",
      "genre_ids": [27],
      "id": 938614,
      "original_language": "en",
      "original_title": "Late Night with the Devil",
      "overview": "1977년 핼러윈 전날 밤, 시청률을 위해서라면 일단 틀고 보는 방송국 놈들 때문에 누구도 예상하지 못한 방송사고 발생! 그리고 마침내 미국 전역을 충격에 빠트렸던 그날 밤의 생방송 악마와의 토크쇼 녹화영상이 최근에 발견됐는데… 47년간 숨겨진, 절대 생중계돼서는 안 될 최악의 토크쇼가 마침내 공개된다, 그동안 공개되지 않은 비하인드 영상과 함께!",
      "popularity": 223.432,
      "poster_path": "/5nUu9y8hQtmW4Qt5GWZZATCjFnN.jpg",
      "release_date": "2024-03-19",
      "title": "악마와의 토크쇼",
      "video": false,
      "vote_average": 7.314,
      "vote_count": 864
    },
    {
      "adult": false,
      "backdrop_path": "/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg",
      "genre_ids": [16, 28, 12, 35, 10751],
      "id": 940551,
      "original_language": "en",
      "original_title": "Migration",
      "overview": "가족을 과잉보호하는 아빠 ‘맥’ 때문에 평생을 작은 연못에서 안전하게 살아온 말러드 가족. 하지만 호기심 가득한 남매 ‘댁스’와 ‘그웬’을 위해 새로운 세상을 모험하고 싶은 엄마 ‘팸’의 설득으로 가족들은 항상 꿈꿔온 자메이카로 생애 첫 가족 모험을 떠나기로 한다! 설렘 넘치는 시작과 달리 태풍을 만나 길을 잃고, 낯선 친구들을 만나고, 위험 가득한 뉴욕에 불시착하게 된다. 인생 처음으로 모든 계획이 틀어지고 위기에 빠진 말러드 가족은 서툴지만 서로를 의지하며 모험을 계속한다. 새로운 세상, 함께라면 두려울 것 없어!",
      "popularity": 250.783,
      "poster_path": "/2xE3NI6zElWhwN9WJ92fqbZKmzZ.jpg",
      "release_date": "2023-12-06",
      "title": "인투 더 월드",
      "video": false,
      "vote_average": 7.446,
      "vote_count": 1712
    },
    {
      "adult": false,
      "backdrop_path": "/4z88bpDf7aqZcYkLDDEIdj8TfZU.jpg",
      "genre_ids": [16, 10751, 14, 28],
      "id": 1011985,
      "original_language": "en",
      "original_title": "Kung Fu Panda 4",
      "overview": "마침내 내면의 평화… 냉면의 평화…가 찾아왔다고 믿는 용의 전사 ‘포’ 이젠 평화의 계곡의 영적 지도자가 되고, 자신을 대신할 후계자를 찾아야만 한다. “이제 용의 전사는 그만둬야 해요?” 용의 전사로의 모습이 익숙해지고 새로운 성장을 하기보다 지금 이대로가 좋은 ‘포’ 하지만 모든 쿵푸 마스터들의 능력을 그대로 복제하는 강력한 빌런 ‘카멜레온’이 나타나고 그녀를 막기 위해 정체를 알 수 없는 쿵푸 고수 ‘젠’과 함께 모험을 떠나게 되는데… 포는 가장 강력한 빌런과 자기 자신마저 뛰어넘고 진정한 변화를 할 수 있을까?",
      "popularity": 316.212,
      "poster_path": "/1ZNOOMmILNUzVYbzG1j7GYb5bEV.jpg",
      "release_date": "2024-03-02",
      "title": "쿵푸팬더 4",
      "video": false,
      "vote_average": 7.099,
      "vote_count": 2535
    },
    {
      "adult": false,
      "backdrop_path": "/p5kpFS0P3lIwzwzHBOULQovNWyj.jpg",
      "genre_ids": [53, 80, 27],
      "id": 1032823,
      "original_language": "en",
      "original_title": "Trap",
      "overview": "10대 딸과 함께 인기 팝스타의 콘서트를 찾은 쿠퍼. 신나게 콘서트를 즐기던 그는 순간 이상한 낌새를 느끼고, 그곳이 최악의 연쇄살인마를 잡기 위한 거대한 덫임을 알게 된다. 그런데 문제는 쿠퍼 자신이 바로 연쇄살인마라는 것! 이제 쿠퍼는 수많은 관객과 경찰을 따돌리고 어린 딸과 함께 무사히 이 덫에서 탈출해야만 하는데…",
      "popularity": 290.786,
      "poster_path": "/2LC4gLNbHpZTq28EWOwCMiVnGcq.jpg",
      "release_date": "2024-07-31",
      "title": "트랩",
      "video": false,
      "vote_average": 6.504,
      "vote_count": 1200
    },
    {
      "adult": false,
      "backdrop_path": "/dn3gbDpXPSwC6saMJOHkCiFA9jn.jpg",
      "genre_ids": [14, 12, 10751, 35],
      "id": 974262,
      "original_language": "en",
      "original_title": "Descendants: The Rise of Red",
      "overview": "하트 여왕이 오라돈을 차지하려고 하자 그의 반항아 딸 레드는 신데렐라의 완벽주의자 딸 클로이와 힘을 합쳐 과거로 돌아가 엄마가 악당의 길로 가지 못하게 막으려 애쓴다.",
      "popularity": 306.797,
      "poster_path": "/lapab2EdLTL6srTus5ktgr64bqF.jpg",
      "release_date": "2024-07-11",
      "title": "디센던츠: 레드의 반항",
      "video": false,
      "vote_average": 6.953,
      "vote_count": 320
    },
    {
      "adult": false,
      "backdrop_path": "/qkEnklEGDFy4TRVhuHFn2DI2BP6.jpg",
      "genre_ids": [27, 53],
      "id": 930600,
      "original_language": "en",
      "original_title": "The Deliverance",
      "overview": "싱글맘 에보니 잭슨은 새출발을 꿈꾸며 가족과 함께 새집으로 이사한다. 그러나 그 집에는 이미 사악한 존재가 도사리고 있는데.",
      "popularity": 288.979,
      "poster_path": "/56CIoE7HeIEiAPuLBF4xYzcOch9.jpg",
      "release_date": "2024-08-16",
      "title": "딜리버런스",
      "video": false,
      "vote_average": 6.256,
      "vote_count": 310
    },
    {
      "adult": false,
      "backdrop_path": "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
      "genre_ids": [12, 18, 878],
      "id": 157336,
      "original_language": "en",
      "original_title": "Interstellar",
      "overview": "세계 각국의 정부와 경제가 완전히 붕괴된 미래가 다가온다. 지난 20세기에 범한 잘못이 전 세계적인 식량 부족을 불러왔고, NASA도 해체되었다. 나사 소속 우주비행사였던 쿠퍼는 지구에 몰아친 식량난으로 옥수수나 키우며 살고 있다. 거센 황사가 몰아친 어느 날 알 수 없는 힘에 이끌려 딸과 함께 도착한 곳은 인류가 이주할 행성을 찾는 나사의 비밀본부. 이 때 시공간에 불가사의한 틈이 열리고, 이 곳을 탐험해 인류를 구해야 하는 임무를 위해 쿠퍼는 만류하는 딸을 뒤로한 채 우주선에 탑승하는데...",
      "popularity": 177.367,
      "poster_path": "/gDN2NWtHbs8ZWEBQM8Dh5OVXdb4.jpg",
      "release_date": "2014-11-05",
      "title": "인터스텔라",
      "video": false,
      "vote_average": 8.4,
      "vote_count": 35242
    },
    {
      "adult": false,
      "backdrop_path": "/hU1Q9YVzdYhokr8a9gLywnSUMlN.jpg",
      "genre_ids": [16, 12, 28, 14, 10751],
      "id": 1147400,
      "original_language": "fr",
      "original_title": "Miraculous World : Paris, Les Aventures de Toxinelle et Griffe Noire",
      "overview": "",
      "popularity": 220.701,
      "poster_path": "/4wHrXw9zB4wsibWaAPDkvjNGPnQ.jpg",
      "release_date": "2023-10-21",
      "title": "Miraculous World : Paris, Les Aventures de Toxinelle et Griffe Noire",
      "video": false,
      "vote_average": 7.241,
      "vote_count": 430
    },
    {
      "adult": false,
      "backdrop_path": "/hU1Q9YVzdYhokr8a9gLywnSUMlN.jpg",
      "genre_ids": [16, 12, 28, 14, 10751],
      "id": 1147400,
      "original_language": "fr",
      "original_title": "Miraculous World : Paris, Les Aventures de Toxinelle et Griffe Noire",
      "overview": "",
      "popularity": 220.701,
      "poster_path": "/4wHrXw9zB4wsibWaAPDkvjNGPnQ.jpg",
      "release_date": "2023-10-21",
      "title": "Miraculous World : Paris, Les Aventures de Toxinelle et Griffe Noire",
      "video": false,
      "vote_average": 7.241,
      "vote_count": 430
    },
    {
      "adult": false,
      "backdrop_path": "/8wwXPG22aNMpPGuXnfm3galoxbI.jpg",
      "genre_ids": [28, 12, 10751, 35],
      "id": 675353,
      "original_language": "en",
      "original_title": "Sonic the Hedgehog 2",
      "overview": "강력한 파워의 ‘너클즈’와 함께 돌아온 천재 과학자 ‘닥터 로보트닉’에 맞서 지구를 구하기 위해 ‘소닉’과 새로운 파트너 ‘테일즈’가 전 세계를 누비는 스피드 액션 블록버스터.",
      "popularity": 174.323,
      "poster_path": "/arCDDZdvamNY628gWJVjlCycf69.jpg",
      "release_date": "2022-03-30",
      "title": "수퍼 소닉 2",
      "video": false,
      "vote_average": 7.506,
      "vote_count": 4901
    },
    {
      "adult": false,
      "backdrop_path": "/bxwKC4qAbceMgHU1xCCTBK1eYdn.jpg",
      "genre_ids": [28, 53, 80],
      "id": 5492,
      "original_language": "en",
      "original_title": "Gunner",
      "overview": "",
      "popularity": 255.898,
      "poster_path": "/eEkAY5veAnwxUOOlpF62KawkFO9.jpg",
      "release_date": "2024-08-16",
      "title": "Gunner",
      "video": false,
      "vote_average": 5.392,
      "vote_count": 83
    },
    {
      "adult": false,
      "backdrop_path": "/en3GU5uGkKaYmSyetHV4csHHiH3.jpg",
      "genre_ids": [10752, 28, 18],
      "id": 929590,
      "original_language": "en",
      "original_title": "Civil War",
      "overview": "극단적 분열로 나눠진 세상, 역사상 최악의 미국 내전 한복판에서 숨막히는 전쟁의 순간들을 생생하게 담아낸 영화",
      "popularity": 287.264,
      "poster_path": "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
      "release_date": "2024-04-10",
      "title": "시빌 워: 분열의 시대",
      "video": false,
      "vote_average": 6.932,
      "vote_count": 2448
    },
    {
      "adult": false,
      "backdrop_path": "/a1m4DAmySexNaaGnjEVA2MKNUCo.jpg",
      "genre_ids": [10402, 36, 18],
      "id": 998846,
      "original_language": "en",
      "original_title": "Back to Black",
      "overview": "영국 싱어송라이터 \u003C에이미 와인하우스\u003E의 데뷔 후 초창기 모습과 앨범 ‘백 투 블랙’ 이야기를 다룬다. 에이미 하우스는 영국을 대표하는 R&B, 솔, 재즈 싱어송라이터로 전 세계 3천만 장 이상의 음반 판매고를 기록했다. 그래미상 5회 수상이라는 기록으로 21세기 최고의 가수로 꼽혔지만 2011년 27살의 젊은 나이에 안타깝게 생을 마감한다.",
      "popularity": 215.757,
      "poster_path": "/xHQEeUT3Ac4fTY72UeNrI75xLtE.jpg",
      "release_date": "2024-04-11",
      "title": "백 투 블랙",
      "video": false,
      "vote_average": 6.711,
      "vote_count": 360
    },
    {
      "adult": false,
      "backdrop_path": "/orTQxcx2aoNpx1DIKTjBzpzvzd0.jpg",
      "genre_ids": [27, 14],
      "id": 1130053,
      "original_language": "en",
      "original_title": "Cinderella's Curse",
      "overview": "",
      "popularity": 281.377,
      "poster_path": "/xegGyjYdCcF9X1FWpfw1O1LcFnZ.jpg",
      "release_date": "2024-05-31",
      "title": "신데렐라의 저주",
      "video": false,
      "vote_average": 5.114,
      "vote_count": 22
    },
    {
      "adult": false,
      "backdrop_path": "/j4CMqgfC8nyLLOYWETXaTInL4Wd.jpg",
      "genre_ids": [10751, 18],
      "id": 1143508,
      "original_language": "en",
      "original_title": "You Gotta Believe",
      "overview": "팀 동료의 병든 아버지에게 시즌을 바친 후, 과소평가되었던 포트워스의 청소년 야구 선수들은 2002년 리틀 리그 월드시리즈까지 신데렐라 스토리를 이어갑니다. 그들은 즉시 ESPN의 클래식으로 자리매김한 기록적인 결승전을 펼칩니다.",
      "popularity": 192.643,
      "poster_path": "/l4X9SeMFCv414BCt97IBgzYX7JC.jpg",
      "release_date": "2024-08-30",
      "title": "믿어야 해",
      "video": false,
      "vote_average": 5,
      "vote_count": 6
    },
    {
      "adult": false,
      "backdrop_path": "/aGQIIKpAPYNtziFrCCBBgIzmUXe.jpg",
      "genre_ids": [27],
      "id": 1051560,
      "original_language": "en",
      "original_title": "The Devil Comes at Night",
      "overview": "",
      "popularity": 280.005,
      "poster_path": "/6QIeZuKirT4cXVpW7ilVZmcRmdK.jpg",
      "release_date": "2023-06-06",
      "title": "The Devil Comes at Night",
      "video": false,
      "vote_average": 7,
      "vote_count": 12
    },
    {
      "adult": false,
      "backdrop_path": "/4ft6TR9wA6bra0RLL6G7JFDQ5t1.jpg",
      "genre_ids": [28, 35],
      "id": 704239,
      "original_language": "en",
      "original_title": "The Union",
      "overview": "뉴저지 출신의 건설 노동자. 추억 속에 남아 있던 고교 시절 여친으로 인해 첩보 임무에 투입되면서 평범한 남자에서 예비 스파이로 거듭난다.",
      "popularity": 293.635,
      "poster_path": "/d9CTnTHip1RbVi2OQbA2LJJQAGI.jpg",
      "release_date": "2024-08-15",
      "title": "더 유니온",
      "video": false,
      "vote_average": 6.275,
      "vote_count": 682
    },
    {
      "adult": false,
      "backdrop_path": "/zJkXE1Y56UqNfYH2TfjEN2fwWbl.jpg",
      "genre_ids": [27, 80, 9648],
      "id": 1023922,
      "original_language": "en",
      "original_title": "MaXXXine",
      "overview": "1980년대 할리우드, 성인 영화 스타이자 신예 여배우인 맥신이 영화에 캐스팅되어 기회를 잡는다. 하지만 의문의 연쇄살인범이 할리우드 배우들을 뒤쫓기 시작하면서 맥신의 과거가 밝혀질 위기에 처하는데...",
      "popularity": 163.58,
      "poster_path": "/ArvoFK6nlouZRxYmtIOUzKIrg90.jpg",
      "release_date": "2024-07-04",
      "title": "맥신",
      "video": false,
      "vote_average": 6.508,
      "vote_count": 569
    },
    {
      "adult": false,
      "backdrop_path": "/jr8tSoJGj33XLgFBy6lmZhpGQNu.jpg",
      "genre_ids": [16, 12, 14, 35, 10751],
      "id": 315162,
      "original_language": "en",
      "original_title": "Puss in Boots: The Last Wish",
      "overview": "아홉 개의 목숨 중 단 하나의 목숨만 남은 장화신은 고양이.  마지막 남은 목숨을 지키기 위해 히어로의 삶 대신 반려묘의 삶을 선택한 그에게 찾아온 마지막 기회, 바로 소원을 들어주는 소원별이 있는 곳을 알려주는 지도!  잃어버린 목숨을 되찾고 다시 히어로가 되기를 꿈꾸는 장화신은 고양이는 뜻밖에 동료가 된 앙숙 파트너 '키티 말랑손', 그저 친구들과 함께라면 모든 게 행복한 강아지 '페로'와 함께 소원별을 찾기 위해 길을 떠난다.  그리고 소원별을 노리는 또 다른 빌런들과 마주치게 되는데…",
      "popularity": 190.284,
      "poster_path": "/rKgvctIuPXyuqOzCQ16VGdnHxKx.jpg",
      "release_date": "2022-12-07",
      "title": "장화신은 고양이: 끝내주는 모험",
      "video": false,
      "vote_average": 8.227,
      "vote_count": 7615
    },
    {
      "adult": false,
      "backdrop_path": "/aswBReNN2adqTiOBnvh96RCDeJP.jpg",
      "genre_ids": [28, 80, 18],
      "id": 959092,
      "original_language": "fr",
      "original_title": "Farang",
      "overview": "새로운 삶을 꿈꾸며 낯선 태국으로 떠난 전직 복서 사미르. 하지만 과거의 적들이 그를 다시 어두운 세계로 끌어들이려 하고, 우연한 사건이 그를 다시 범죄의 소용돌이로 몰아넣는다. 결국 평화롭게 살아가던 그의 가정에 비극이 찾아오고, 이제 복수만이 유일한 출로가 된다. 이제 그는 딸을 지키기 위해, 가장 위험한 선택을 감행한다.",
      "popularity": 202.017,
      "poster_path": "/whgxOvEisQTM16MxngaQjFBPcqj.jpg",
      "release_date": "2023-06-28",
      "title": "파랑",
      "video": false,
      "vote_average": 6.675,
      "vote_count": 154
    },
    {
      "adult": false,
      "backdrop_path": "/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
      "genre_ids": [18, 28, 80, 53],
      "id": 155,
      "original_language": "en",
      "original_title": "The Dark Knight",
      "overview": "범죄와 부정부패를 제거하여 고담시를 지키려는 배트맨. 그는 짐 고든 형사와 패기 넘치는 고담시 지방 검사 하비 덴트와 함께 도시를 범죄 조직으로부터 영원히 구원하고자 한다. 세 명의 의기투합으로 위기에 처한 악당들이 모인 자리에 보라색 양복을 입고 얼굴에 짙게 화장을 한 괴이한 존재가 나타나 배트맨을 죽이자는 사상 초유의 제안을 한다. 그는 바로 어떠한 룰도, 목적도 없는 사상 최악의 악당 미치광이 살인광대 조커. 배트맨을 죽이고 고담시를 끝장내버리기 위한 조커의 광기 어린 행각에 도시는 혼란에 빠지는데...",
      "popularity": 170.196,
      "poster_path": "/f6dNinWX8rBM79JXKcShkfSh2oA.jpg",
      "release_date": "2008-07-16",
      "title": "다크 나이트",
      "video": false,
      "vote_average": 8.516,
      "vote_count": 32593
    },
    {
      "adult": false,
      "backdrop_path": "/yHzyPJrVqlTySQ9mc379yxrLBYQ.jpg",
      "genre_ids": [12, 14],
      "id": 672,
      "original_language": "en",
      "original_title": "Harry Potter and the Chamber of Secrets",
      "overview": "해리 포터에겐 이번 여름방학이 별로 즐겁질 못했다. 마법이라면 질색을 하는 페투니아 이모와 버논 이모부의 구박도 그렇지만, 무엇보다 속상한 건 단짝이었던 론 위즐리와 헤르미온느 그레인저가 그 사이 자신을 까맣게 잊었는지 자신의 편지에 답장 한 통 없다는 것.  그러던 어느날 꼬마 집요정 도비가 해리의 침실에 나타나 뜻밖의 얘기를 한다. 호그와트 마법학교로 돌아가면 무서운 일을 당할 거라는 것. 도비는 해리를 학교에 못 가게 하려고 자신이 여태까지 론과 헤르미온느의 답장을 가로채 왔음을 고백한다. 그러나 도비와 더즐리 가족의 방해에도 불구, 해리는 론과 그의 형제들이 타고 온 하늘을 나는 자동차를 타고 이모집을 탈출, 따뜻한 가족애가 넘치는 론의 집으로 가는데...",
      "popularity": 193.597,
      "poster_path": "/sfs4U6XpiKFngbbSzrpZbkM1ySI.jpg",
      "release_date": "2002-11-13",
      "title": "해리 포터와 비밀의 방",
      "video": false,
      "vote_average": 7.72,
      "vote_count": 21699
    },
    {
      "adult": false,
      "backdrop_path": "/diVcZzeebNQuT4wKiflNP76VcsY.jpg",
      "genre_ids": [35, 878, 28],
      "id": 1094138,
      "original_language": "en",
      "original_title": "Jackpot!",
      "overview": "가까운 미래, 해가 지기 전 당첨자를 죽이면 합법적으로 수십억 달러의 당첨금을 가질 수 있는 '그랜드 복권'이 생겨난다. 케이티 김은 의도치 않게 당첨 복권을 갖게 되며 아마추어 복권 당첨자 경호원으로 일하는 노엘 캐시디와 마지못해 힘을 합치고, 노엘은 상금의 일부를 받는 대가로 케이티를 일몰까지 지켜야만 한다.",
      "popularity": 261.428,
      "poster_path": "/j1pmELLsuQrZItCmOrj4HU20c43.jpg",
      "release_date": "2024-08-13",
      "title": "잭팟!",
      "video": false,
      "vote_average": 6.425,
      "vote_count": 485
    },
    {
      "adult": false,
      "backdrop_path": "/m2teNSCH7sxkuXHossRJXhxPKeT.jpg",
      "genre_ids": [878, 10751, 35, 28, 12],
      "id": 939243,
      "original_language": "en",
      "original_title": "Sonic the Hedgehog 3",
      "overview": "",
      "popularity": 208.662,
      "poster_path": "/ynKEIxoAPTyaK9YaIwsj6htROTu.jpg",
      "release_date": "2024-12-19",
      "title": "수퍼 소닉 3",
      "video": false,
      "vote_average": 0,
      "vote_count": 0
    },
    {
      "adult": false,
      "backdrop_path": "/pnhUBMJFaJzk9AO3h1akhzj3syu.jpg",
      "genre_ids": [18, 80, 53],
      "id": 889737,
      "original_language": "en",
      "original_title": "Joker: Folie à Deux",
      "overview": "2년 전, 세상을 뒤흔들며 고담시 아이콘으로 자리한 ‘아서 플렉’은 아캄 수용소에 갇혀 최종 재판을 앞둔 무기력한 삶을 살아간다. 그러던 어느 날, 수용소에서 운명적으로 만난 ‘리 퀸젤’은 ‘아서’의 삶을 다시 뒤바꾸며 그의 마음 속에 잠들어 있던 ‘조커’를 깨우고 ‘리’ 역시 각성하며 자신을 ‘할리 퀸’이라 지칭하며 서로에게 깊이 빠져든다. 무고한 시민을 죽인 죄로 재판에 오르게 된 ‘아서’ 그는 최후의 심판대에서 ‘할리 퀸’과 함께 자신, ‘조커’의 이야기를 시작하는데…",
      "popularity": 257.768,
      "poster_path": "/dA1TGJPTVjlqPc8PiEE2PfvFBUp.jpg",
      "release_date": "2024-10-01",
      "title": "조커: 폴리 아 되",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 6
    },
    {
      "adult": false,
      "backdrop_path": "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
      "genre_ids": [878, 28, 12],
      "id": 580489,
      "original_language": "en",
      "original_title": "Venom: Let There Be Carnage",
      "overview": "‘베놈'과 완벽한 파트너가 된 ‘에디 브록' 앞에 ‘클리터스 캐서디'가 ‘카니지'로 등장, 앞으로 닥칠 대혼돈의 세상을 예고한다. 대혼돈의 시대가 시작되고, 악을 악으로 처단할 것인가?",
      "popularity": 178.943,
      "poster_path": "/fHnKlSp28U648O4vm95z86Jw5tT.jpg",
      "release_date": "2021-09-30",
      "title": "베놈 2: 렛 데어 비 카니지",
      "video": false,
      "vote_average": 6.796,
      "vote_count": 9920
    },
    {
      "adult": false,
      "backdrop_path": "/5rrGVmRUuCKVbqUu41XIWTXJmNA.jpg",
      "genre_ids": [12, 14],
      "id": 674,
      "original_language": "en",
      "original_title": "Harry Potter and the Goblet of Fire",
      "overview": "요즘 들어 매일 꾸는 악몽 때문에 이마의 상처에 더욱 통증을 느끼는 해리는 친구 론과 헤르미온느와 함께 퀴디치 월드컵에 참가해 악몽에서 벗어날 수 있게 돼 마냥 기쁘다. 그러나 퀴디치 캠프장 근방 하늘에 불길한 기운이 나타난다. 바로 마왕 볼드모트의 상징인 어둠의 표식이 나타난 것. 볼드모트가 13년 전에 자취를 감춘 뒤, 감히 모습을 드러내지 못했던 그의 추종자 데스 이터들이 그 표식을 불러낸 것이다. 두려움으로 가득 찬 해리는 안전한 호그와트 마법학교로 돌아가고 싶어한다. 덤블도어 교장이라면 자신을 지켜줄 수 있을 것이기에. 그러나 올해는 예년과 상황이 좀 다른데...",
      "popularity": 180.625,
      "poster_path": "/h6BhNwNXg0IEbs2PoWfCX9QEvgl.jpg",
      "release_date": "2005-11-16",
      "title": "해리 포터와 불의 잔",
      "video": false,
      "vote_average": 7.8,
      "vote_count": 20444
    },
    {
      "adult": false,
      "backdrop_path": "/l0Y9OzRWKmlzZcGy4olKaOPXsru.jpg",
      "genre_ids": [10749, 14, 16],
      "id": 3933,
      "original_language": "en",
      "original_title": "Corpse Bride",
      "overview": "생선 통조림 공장을 하며 벼락부자가 된 반 도르트 일가와 세습귀족이지만 가난한 에버글롯 일가는 각기 서로의 신분과 재산 때문에 사돈으로서의 연을 맺기로 결정한다. 결혼식 전날, 예행연습을 위해 처음 만나게 된 빅터와 빅토리아. 두 사람은 쑥스럽고 어색한 분위기 속에서도 사랑의 가능성을 발견하게 된다. 하지만 빅터는 결혼 리허설에서 계속해서 실수를 저지르고 급기야 연습을 더 하고 오라며 갤스웰 목사에게 쫓겨난다. 숲 속에서 홀로 연습하던 도중, 땅 위로 튀어나온 손가락 뼈에 반지를 끼웠다가 유령 신부의 오해로 지하세계에 끌려가게 되는 색다른 경험을 하게 된다.",
      "popularity": 177.704,
      "poster_path": "/AinoobwUR3mDspc1O9exQHgUAyv.jpg",
      "release_date": "2005-09-12",
      "title": "유령 신부",
      "video": false,
      "vote_average": 7.565,
      "vote_count": 8979
    },
    {
      "adult": false,
      "backdrop_path": "/6MuKvMcnNdgbfhc7HRGDbDSJuR7.jpg",
      "genre_ids": [18, 35],
      "id": 1154762,
      "original_language": "en",
      "original_title": "His Three Daughters",
      "overview": "병든 아버지의 마지막 나날을 함께하기 위해 뉴욕의 비좁은 아파트에 모인 세 자매. 서로 소원하게 지내던 세 사람 사이에 격렬한 감정이 소용돌이친다.",
      "popularity": 174.218,
      "poster_path": "/onibF7H6pHequ5XyLGMvD79oE4j.jpg",
      "release_date": "2024-09-05",
      "title": "아버지의 세 딸들",
      "video": false,
      "vote_average": 7.021,
      "vote_count": 70
    },
    {
      "adult": false,
      "backdrop_path": "/rSRA1p4e3laAAJflzdgtqNlx27Y.jpg",
      "genre_ids": [28],
      "id": 1049574,
      "original_language": "en",
      "original_title": "Darkness of Man",
      "overview": "",
      "popularity": 246.638,
      "poster_path": "/zgZ05k3m1XePSi5nJ0ZKQo5AXWY.jpg",
      "release_date": "2024-05-07",
      "title": "Darkness of Man",
      "video": false,
      "vote_average": 6.689,
      "vote_count": 127
    },
    {
      "adult": false,
      "backdrop_path": "/kwzNUM4yZ26XuNAPSyaWwJeWRP4.jpg",
      "genre_ids": [28, 35, 14],
      "id": 950526,
      "original_language": "pt",
      "original_title": "O Mestre da Fumaça",
      "overview": "",
      "popularity": 219.538,
      "poster_path": "/tYKoNjCOQ9dbXaQnHRiJ3bQ6Fjk.jpg",
      "release_date": "2023-05-18",
      "title": "O Mestre da Fumaça",
      "video": false,
      "vote_average": 7.545,
      "vote_count": 67
    },
    {
      "adult": false,
      "backdrop_path": "/obKmfNexgL4ZP5cAmzdL4KbHHYX.jpg",
      "genre_ids": [12, 14],
      "id": 673,
      "original_language": "en",
      "original_title": "Harry Potter and the Prisoner of Azkaban",
      "overview": "13세가 된 해리 포터는 또 한번의 여름 방학을 이모 가족인 더즐리 일가와 우울하게 보내야 했다. 물론 마법을 쓰는 건 일체 금지. 하지만, 버논 이모부의 누이인 마지 아줌마가 더즐리 가를 방문하면서 상황은 변한다. 위압적인 마지는 해리에겐 늘 공포의 대상. 마지 아줌마 때문에 스트레스를 받던 해리는 급기야 실수로 그녀를 거대한 괴물 풍선으로 만들어 하늘 높이 띄워 보내버리고 만다. 이모와 이모부에게 벌을 받을 것도 두렵고, 일반 세상에선 마법 사용이 금지돼 있는 것을 어겼기 때문에 호그와트 마법학교와 마법부의 징계가 걱정된 해리는 밤의 어둠 속으로 도망치지만, 순식간에 근사한 보라색 3층 버스에 태워져 한 술집으로 인도되고 마는데...",
      "popularity": 189.424,
      "poster_path": "/anwNl1xbzXoj5Ax1nVw3WoDzHlw.jpg",
      "release_date": "2004-05-31",
      "title": "해리 포터와 아즈카반의 죄수",
      "video": false,
      "vote_average": 8.019,
      "vote_count": 21323
    },
    {
      "adult": false,
      "backdrop_path": "/6bGmHzPEq2n6g17moqWwDpJBEom.jpg",
      "genre_ids": [27, 9648, 53],
      "id": 1041613,
      "original_language": "en",
      "original_title": "Immaculate",
      "overview": "순수하고 신실한 믿음을 가진 수녀 '세실리아'. 어느 비밀스러운 수녀원의 초청을 받아 낯선 생활에 적응해 가던 중 처녀의 몸으로 임신을 했다는 사실이 밝혀지고 기적의 주인공으로 추앙 받기 시작하는데… 순결한 수녀의 임신, 축복인가 저주인가!",
      "popularity": 144.65,
      "poster_path": "/kQgBxZQOgC3aFjXC0E1qGujkQyn.jpg",
      "release_date": "2024-03-20",
      "title": "이매큘레이트",
      "video": false,
      "vote_average": 6.303,
      "vote_count": 1059
    },
    {
      "adult": false,
      "backdrop_path": "/9h8lN8CExMulqDmYg9hLpz8TvvP.jpg",
      "genre_ids": [16, 878],
      "id": 14258,
      "original_language": "ko",
      "original_title": "원더풀 데이즈",
      "overview": "인공지능도시 ‘에코반’의 심장부, ‘델로스 센터’에 침입자가 발생한다. 에코반 순찰대원 제이는 그가 첫사랑 수하임을 알게 된다. 하늘은 잿빛이 아니라 푸른빛이라고, 언젠가 꼭 푸른 하늘을 보여주고 싶다고 말했던 수하. 그러나 갑자기 에코반을 떠났고 사람들은 모두 그가 죽었다고 했다. 기다렸던 첫사랑을 적으로 만난 제이는 혼란에 휩싸이고, 제이를 사랑하는 경비대장 시몬 역시 수하의 존재를 알게 되는데...  잿빛 하늘이 계속되는 지구. 살아남은 사람들은 남태평양의 ‘시실섬’에 모여 도시를 건설한다. 과학자들과 권력자들은 오염물질을 에너지원으로 하는 인공 지능 도시 ‘에코반’을 건설하고, 방사능에 노출된 난민들을 받아들이지 않는다. 에코반에서 버려진 난민들은 ‘마르’라는 지역에 터전을 마련한다. 에코반이 건설된 지 100년 후, 오염된 대기가 점차 맑아지자 ‘마르’의 오염된 대기를 에너지원으로 삼았던 ‘에코반’은 도시의 특성상 오염물질이 계속 필요하게 되고, 급기야 에너지 확보를 위해 마르 전역을 불태워 도시의 생명을 이어가려는 음모를 계획한다.",
      "popularity": 225.972,
      "poster_path": "/5l5D3uBDEihYUpKFrNSBEherrgb.jpg",
      "release_date": "2003-07-17",
      "title": "원더풀 데이즈",
      "video": false,
      "vote_average": 6.1,
      "vote_count": 151
    },
    {
      "adult": false,
      "backdrop_path": "/y4NzXdvpJdwRmsnOT7HdkmHh6Yn.jpg",
      "genre_ids": [878, 12, 28],
      "id": 748167,
      "original_language": "en",
      "original_title": "Uglies",
      "overview": "표준화된 아름다움을 강요하는 미래의 디스토피아에서, 성형 수술 의례를 앞둔 청소년이 사라진 친구를 찾아 기나긴 여정을 시작한다.",
      "popularity": 229.394,
      "poster_path": "/a6CUf7p15OwhlFTlqgkwSh2H1Zk.jpg",
      "release_date": "2024-09-12",
      "title": "어글리",
      "video": false,
      "vote_average": 6.056,
      "vote_count": 411
    },
    {
      "adult": false,
      "backdrop_path": "/x2thJwMJ6oGlhn7UC4vSwHltEw0.jpg",
      "genre_ids": [28, 53, 10770],
      "id": 1115396,
      "original_language": "en",
      "original_title": "Hunting Games",
      "overview": "",
      "popularity": 258.302,
      "poster_path": "/xVbEJzdMxIQqpuLgla0hU8qr9mt.jpg",
      "release_date": "2023-05-12",
      "title": "Hunting Games",
      "video": false,
      "vote_average": 4.107,
      "vote_count": 14
    },
    {
      "adult": false,
      "backdrop_path": "/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg",
      "genre_ids": [878, 28, 12],
      "id": 24428,
      "original_language": "en",
      "original_title": "The Avengers",
      "overview": "에너지원 큐브를 이용한 적의 등장으로 인류가 위험에 처하자 국제평화유지기구인 쉴드의 국장 닉 퓨리는 어벤져스 작전을 위해 전 세계에 흩어져 있던 슈퍼히어로들을 찾아나선다. 아이언맨부터 토르, 헐크, 캡틴 아메리카는 물론, 쉴드의 요원인 블랙 위도우, 호크 아이까지, 최고의 슈퍼히어로들이 어벤져스의 멤버로 모이게 되지만, 각기 개성이 강한 이들의 만남은 예상치 못한 방향으로 흘러가는데...",
      "popularity": 146.42,
      "poster_path": "/krgjV3rJtBcEpQehODKXNCt6uFL.jpg",
      "release_date": "2012-04-25",
      "title": "어벤져스",
      "video": false,
      "vote_average": 7.718,
      "vote_count": 30520
    },
    {
      "adult": false,
      "backdrop_path": "/pnhUBMJFaJzk9AO3h1akhzj3syu.jpg",
      "genre_ids": [18, 80, 53],
      "id": 889737,
      "original_language": "en",
      "original_title": "Joker: Folie à Deux",
      "overview": "2년 전, 세상을 뒤흔들며 고담시 아이콘으로 자리한 ‘아서 플렉’은 아캄 수용소에 갇혀 최종 재판을 앞둔 무기력한 삶을 살아간다. 그러던 어느 날, 수용소에서 운명적으로 만난 ‘리 퀸젤’은 ‘아서’의 삶을 다시 뒤바꾸며 그의 마음 속에 잠들어 있던 ‘조커’를 깨우고 ‘리’ 역시 각성하며 자신을 ‘할리 퀸’이라 지칭하며 서로에게 깊이 빠져든다. 무고한 시민을 죽인 죄로 재판에 오르게 된 ‘아서’ 그는 최후의 심판대에서 ‘할리 퀸’과 함께 자신, ‘조커’의 이야기를 시작하는데…",
      "popularity": 257.768,
      "poster_path": "/dA1TGJPTVjlqPc8PiEE2PfvFBUp.jpg",
      "release_date": "2024-10-01",
      "title": "조커: 폴리 아 되",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 6
    },
    {
      "adult": false,
      "backdrop_path": "/8AGwtYlvrZWEPo9zQthVd68zxNO.jpg",
      "genre_ids": [27],
      "id": 1140168,
      "original_language": "en",
      "original_title": "Freddy's Fridays",
      "overview": "",
      "popularity": 219.147,
      "poster_path": "/8smsOtjp8FbBgL8YKrgCADJWEhe.jpg",
      "release_date": "2023-10-13",
      "title": "Freddy's Fridays",
      "video": false,
      "vote_average": 3.778,
      "vote_count": 9
    },
    {
      "adult": false,
      "backdrop_path": "/iafs5DG5fGq7ef0acl3xlX4BFrs.jpg",
      "genre_ids": [18, 10770],
      "id": 1219685,
      "original_language": "fr",
      "original_title": "Un père idéal",
      "overview": "",
      "popularity": 263.045,
      "poster_path": "/4xJd3uwtL1vCuZgEfEc8JXI9Uyx.jpg",
      "release_date": "2024-04-21",
      "title": "Un père idéal",
      "video": false,
      "vote_average": 6.438,
      "vote_count": 96
    },
    {
      "adult": false,
      "backdrop_path": "/bsaA9qtIR6VTDQykXdBzJc8V5rS.jpg",
      "genre_ids": [12, 14],
      "id": 675,
      "original_language": "en",
      "original_title": "Harry Potter and the Order of the Phoenix",
      "overview": "길고도 지루한 여름 날 호그와트 마법학교 다섯 번째 해를 기다리고 있는 해리포터. 이모부 더즐리 식구들과 참고 사는 것도 지겨운데다 친구 론과 헤르미온느에게서는 편지 한 통 오지 않는다. 그러던 중 예상치 못했던 편지 한 장이 도착한다. 그것은 해리가 학교 밖인 리틀 위닝에서 얄미운 사촌 두들리, 즉 머글 앞에서 디멘터들의 공격을 막는 마법을 사용했기 때문에 호그와트 마법학교에서 퇴학 당하게 되었다는 소식이었다. 앞이 캄캄한 해리. 갑자기 어둠의 마법사 오러들이 나타나 해리를 불사조 기사단의 비밀 장소로 데리고 가는데...",
      "popularity": 147.95,
      "poster_path": "/1ItejykqHTbFWbZXdzqlvqriv7K.jpg",
      "release_date": "2007-07-08",
      "title": "해리 포터와 불사조 기사단",
      "video": false,
      "vote_average": 7.68,
      "vote_count": 19236
    },
    {
      "adult": false,
      "backdrop_path": "/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg",
      "genre_ids": [28, 878, 12],
      "id": 912649,
      "original_language": "en",
      "original_title": "Venom: The Last Dance",
      "overview": "환상의 케미스트리의 에디 브록과 그의 심비오트 베놈은 그들을 노리는 정체불명 존재의 추격을 피해 같이 도망을 다니게 된다. 한편 베놈의 창조자 ‘널’은 고향 행성에서부터 그들을 찾아내기 위해 지구를 침략하고 에디와 베놈은 그동안 겪어보지 못한 최악의 위기를 맞이하게 되는데…",
      "popularity": 218.347,
      "poster_path": "/3flIDcZF3tnR7m5OU2h7lLPQwmr.jpg",
      "release_date": "2024-10-23",
      "title": "베놈: 라스트 댄스",
      "video": false,
      "vote_average": 0,
      "vote_count": 0
    },
    {
      "adult": false,
      "backdrop_path": "/j29ekbcLpBvxnGk6LjdTc2EI5SA.jpg",
      "genre_ids": [16, 10751, 12, 18, 35],
      "id": 150540,
      "original_language": "en",
      "original_title": "Inside Out",
      "overview": "모든 사람의 머릿속에 존재하는 감정 컨트롤 본부. 그곳에서 불철주야 열심히 일하는 기쁨, 슬픔, 버럭, 까칠, 소심 다섯 감정들. 정든 옛 동네를 떠나 도시로 이사하는 라일리 가족. 이사 후 새로운 환경에 적응해야 하는 라일리를 위해 그 어느 때 보다 바쁘게 감정의 신호를 보내지만 우연한 실수로 기쁨과 슬픔이 본부를 이탈하게 되자 라일리의 마음 속에 큰 변화가 찾아온다. 라일리가 예전의 모습을 되찾기 위해서는 기쁨과 슬픔이 본부로 돌아가야만 한다. 그러나 엄청난 기억들이 저장되어 있는 머릿속 세계에서 본부까지 가는 길은 험난하기만 한데...",
      "popularity": 216.535,
      "poster_path": "/rMXHvHzpuYZXrJUhRVJ3TvDSwe5.jpg",
      "release_date": "2015-06-17",
      "title": "인사이드 아웃",
      "video": false,
      "vote_average": 7.914,
      "vote_count": 21685
    },
    {
      "adult": false,
      "backdrop_path": "/f7Qwg7kKNIvBnr3Ipv2bpXb23BN.jpg",
      "genre_ids": [27, 9648, 878, 53],
      "id": 1024721,
      "original_language": "en",
      "original_title": "Monolith",
      "overview": "명예를 실추한 한 기자가 탐사 팟캐스트로 전환하여 기자로서의 커리어를 회복하기 위해 고군분투한다. 그 과정에서 외계인의 음모와 관련이 있을지도 모르는 이상한 유물에 대해 알게 되고, 그 진실을 파헤치던 중 자신을 둘러싼 이야기의 거짓들 역시 드러나기 시작한다.",
      "popularity": 164.136,
      "poster_path": "/zKpLzzX1va6gkMJiI9p3DudqChe.jpg",
      "release_date": "2023-10-26",
      "title": "모놀리스",
      "video": false,
      "vote_average": 5.928,
      "vote_count": 90
    },
    {
      "adult": false,
      "backdrop_path": "/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg",
      "genre_ids": [16, 10751, 12, 14, 35],
      "id": 502356,
      "original_language": "en",
      "original_title": "The Super Mario Bros. Movie",
      "overview": "따단-딴-따단-딴 ♫ 전 세계를 열광시킬 올 타임 슈퍼 어드벤처의 등장! 뉴욕의 평범한 배관공 형제 '마리오'와 ‘루이지’는 배수관 고장으로 위기에 빠진 도시를 구하려다 미스터리한 초록색 파이프 안으로 빨려 들어가게 된다. 파이프를 통해 새로운 세상으로 차원 이동하게 된 형제. 형 '마리오'는 뛰어난 리더십을 지닌 '피치'가 통치하는 버섯왕국에 도착하지만 동생 '루이지'는 빌런 '쿠파'가 있는 다크랜드로 떨어지며 납치를 당하고 ‘마리오’는 동생을 구하기 위해 ‘피치’와 ‘키노피오’의 도움을 받아 '쿠파'에 맞서기로 결심한다. 그러나 슈퍼스타로 세상을 지배하려는 그의 강력한 힘 앞에 이들은 예기치 못한 위험에 빠지게 되는데...!",
      "popularity": 213.599,
      "poster_path": "/jt1GlLLvkWL2m83VX8I1qsDR187.jpg",
      "release_date": "2023-04-05",
      "title": "슈퍼 마리오 브라더스",
      "video": false,
      "vote_average": 7.7,
      "vote_count": 8932
    },
    {
      "adult": false,
      "backdrop_path": "/dsGwCEO8tda4FlgHKvL95f0oQbH.jpg",
      "genre_ids": [16, 878, 28],
      "id": 1209290,
      "original_language": "en",
      "original_title": "Justice League: Crisis on Infinite Earths Part Three",
      "overview": "",
      "popularity": 215.049,
      "poster_path": "/a3q8NkM8uTh9E23VsbUOdDSbBeN.jpg",
      "release_date": "2024-07-15",
      "title": "저스티스 리그: 크라이시스 온 인피닛 어스 파트 원",
      "video": false,
      "vote_average": 7.482,
      "vote_count": 192
    },
    {
      "adult": false,
      "backdrop_path": "/vr6n6ZFUZvedvIlhfYcbCWcaKyW.jpg",
      "genre_ids": [12, 14, 28],
      "id": 58,
      "original_language": "en",
      "original_title": "Pirates of the Caribbean: Dead Man's Chest",
      "overview": "잭 스패로우는 블랙펄을 되찾아 포트 로열을 떠났지만 그를 기다리는 것은 수평선만이 아니었다. 유령선 플라잉 더치맨의 선장 데이비 존스는 잭이 자신에게 피로 진 빚이 있다면서 빚을 갚거나 영혼을 내놓으라고 요구한다. 불행 중 다행한 것은 잭에게 피의 빚 외에도 중매의 은총이 있었다는 것. 결혼을 앞둔 윌 터너와 엘리자베스 스완은 만사를 제쳐두고 옛 친구를 도우러 온다. 잭을 구할 수 있는 단 한 가지 방법은 세상 끝에 있다는 망자의 함을 찾는 것 뿐인데...",
      "popularity": 133.997,
      "poster_path": "/6tD4oT7C01aZLVfoZDz5VFVbJCi.jpg",
      "release_date": "2006-07-06",
      "title": "캐리비안의 해적: 망자의 함",
      "video": false,
      "vote_average": 7.364,
      "vote_count": 15757
    },
    {
      "adult": false,
      "backdrop_path": "/c3rwwFFVbkyEI6wPtpPd9lvovPW.jpg",
      "genre_ids": [28, 36],
      "id": 1311550,
      "original_language": "en",
      "original_title": "House of Ga'a",
      "overview": "전성기 시절의 오요 제국에서 왕좌를 좌지우지하던 바쇼룬 가아. 이 흉포한 성격의 킹메이커는 왕보다 막강한 권세를 누렸으나, 결국 자기 혈육의 손에 거세당하며 최후를 맞이한다.",
      "popularity": 216.959,
      "poster_path": "/6yK9hmS641NMwRkR1wWAALWI34t.jpg",
      "release_date": "2024-07-26",
      "title": "킹메이커 가아",
      "video": false,
      "vote_average": 5.929,
      "vote_count": 70
    }
]"""

@Serializable
data class Movie(
    val adult: Boolean = false,
    val backdrop_path: String? = "",
    val genre_ids: List<Int> = listOf(1, 0),
    val id: Int = 0,
    val original_language: String = "en",
    val original_title: String = "",
    val overview: String = "",
    val popularity: Float,
    val poster_path: String = "",
    val release_date: String = "",
    val title: String = "",
    val video: Boolean = true,
    val vote_average: Float,
    val vote_count: Int = 0
)


fun parseMovieList(jsonString: String): List<Movie> {
    return Json.decodeFromString(jsonString)
}

val MovieData1: List<Movie> = parseMovieList(MovieDataString1)
val MovieData2: List<Movie> = parseMovieList(MovieDataString2)
val MovieData3: List<Movie> = parseMovieList(MovieDataString3)

val MovieData: List<Movie> = MovieData1 + MovieData2 + MovieData3

const val GenreListString = """
    [
    {
      "id": 28,
      "name": "액션"
    },
    {
      "id": 12,
      "name": "모험"
    },
    {
      "id": 16,
      "name": "애니메이션"
    },
    {
      "id": 35,
      "name": "코미디"
    },
    {
      "id": 80,
      "name": "범죄"
    },
    {
      "id": 99,
      "name": "다큐멘터리"
    },
    {
      "id": 18,
      "name": "드라마"
    },
    {
      "id": 10751,
      "name": "가족"
    },
    {
      "id": 14,
      "name": "판타지"
    },
    {
      "id": 36,
      "name": "역사"
    },
    {
      "id": 27,
      "name": "공포"
    },
    {
      "id": 10402,
      "name": "음악"
    },
    {
      "id": 9648,
      "name": "미스터리"
    },
    {
      "id": 10749,
      "name": "로맨스"
    },
    {
      "id": 878,
      "name": "SF"
    },
    {
      "id": 10770,
      "name": "TV 영화"
    },
    {
      "id": 53,
      "name": "스릴러"
    },
    {
      "id": 10752,
      "name": "전쟁"
    },
    {
      "id": 37,
      "name": "서부"
    }
  ]
"""


@Serializable
class Genre(
    val id: Int,
    val name: String,
)

fun parseGenreList(jsonString: String): List<Genre> {
    return Json.decodeFromString(jsonString)
}

val GenreList: List<Genre> = parseGenreList(GenreListString)
